services:
  backend:
    build:
      context: ./
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:pizza_password@mydb:5432/mydb
      - CHOKIDAR_USEPOLLING=true
    depends_on: 
      - db
    volumes:
      - .:/app
      - /app/node_modules  
  db:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pizza_password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"